#ifndef STYLESHEET_H
#define STYLESHEET_H

#include <QString>

namespace StyleSheet {

inline QString darkTheme()
{
    return QStringLiteral(
        /* ── Global ── */
        "QWidget {"
        "    background-color: #12131a;"
        "    color: #dde1f0;"
        "    font-family: 'Segoe UI', sans-serif;"
        "    font-size: 13px;"
        "}"

        /* ── QMainWindow / central ── */
        "QMainWindow {"
        "    background-color: #12131a;"
        "}"

        /* ── QTabWidget ── */
        "QTabWidget::pane {"
        "    border: 1px solid #353650;"
        "    background-color: #1e1f2e;"
        "}"
        "QTabBar::tab {"
        "    background-color: #252638;"
        "    color: #dde1f0;"
        "    border: 1px solid #353650;"
        "    border-bottom: none;"
        "    padding: 6px 18px;"
        "    margin-right: 2px;"
        "    border-top-left-radius: 4px;"
        "    border-top-right-radius: 4px;"
        "}"
        "QTabBar::tab:selected {"
        "    background-color: #1e1f2e;"
        "    color: #00c8d7;"
        "    border-top: 2px solid #00c8d7;"
        "}"
        "QTabBar::tab:hover:!selected {"
        "    background-color: #2e2f48;"
        "    color: #00c8d7;"
        "}"

        /* ── QGroupBox ── */
        "QGroupBox {"
        "    background-color: #1e1f2e;"
        "    border: 1px solid #353650;"
        "    border-radius: 6px;"
        "    margin-top: 18px;"
        "    padding: 6px;"
        "    font-weight: bold;"
        "    color: #00c8d7;"
        "}"
        "QGroupBox::title {"
        "    subcontrol-origin: margin;"
        "    subcontrol-position: top left;"
        "    padding: 2px 8px;"
        "    color: #00c8d7;"
        "    font-size: 12px;"
        "    letter-spacing: 0.5px;"
        "}"

        /* ── QPushButton ── */
        "QPushButton {"
        "    background-color: #252638;"
        "    color: #dde1f0;"
        "    border: 1px solid #00c8d7;"
        "    border-radius: 4px;"
        "    padding: 5px 14px;"
        "    font-size: 13px;"
        "}"
        "QPushButton:hover {"
        "    background-color: #00c8d7;"
        "    color: #12131a;"
        "}"
        "QPushButton:pressed {"
        "    background-color: #0099a8;"
        "    color: #12131a;"
        "}"
        "QPushButton:disabled {"
        "    background-color: #1e1f2e;"
        "    color: #555770;"
        "    border-color: #353650;"
        "}"
        "QPushButton#stopButton {"
        "    background-color: #f44336;"
        "    border-color: #f44336;"
        "    color: #ffffff;"
        "    font-weight: bold;"
        "    font-size: 15px;"
        "}"
        "QPushButton#stopButton:hover {"
        "    background-color: #e53935;"
        "}"
        "QPushButton#stopButton:pressed {"
        "    background-color: #b71c1c;"
        "}"

        /* ── QSlider ── */
        "QSlider::groove:horizontal {"
        "    height: 4px;"
        "    background: #353650;"
        "    border-radius: 2px;"
        "}"
        "QSlider::handle:horizontal {"
        "    background: #00c8d7;"
        "    border: none;"
        "    width: 14px;"
        "    height: 14px;"
        "    margin: -5px 0;"
        "    border-radius: 7px;"
        "}"
        "QSlider::sub-page:horizontal {"
        "    background: #00c8d7;"
        "    border-radius: 2px;"
        "}"

        /* ── QDoubleSpinBox / QSpinBox ── */
        "QDoubleSpinBox, QSpinBox {"
        "    background-color: #252638;"
        "    color: #dde1f0;"
        "    border: 1px solid #353650;"
        "    border-radius: 3px;"
        "    padding: 3px 6px;"
        "    font-family: 'Consolas', monospace;"
        "    font-size: 12px;"
        "    min-width: 70px;"
        "}"
        "QDoubleSpinBox:focus, QSpinBox:focus {"
        "    border-color: #00c8d7;"
        "}"
        "QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,"
        "QSpinBox::up-button, QSpinBox::down-button {"
        "    background-color: #353650;"
        "    border: none;"
        "    width: 16px;"
        "}"
        "QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,"
        "QSpinBox::up-button:hover, QSpinBox::down-button:hover {"
        "    background-color: #00c8d7;"
        "}"

        /* ── QLineEdit ── */
        "QLineEdit {"
        "    background-color: #252638;"
        "    color: #dde1f0;"
        "    border: 1px solid #353650;"
        "    border-radius: 3px;"
        "    padding: 4px 8px;"
        "    font-size: 13px;"
        "}"
        "QLineEdit:focus {"
        "    border-color: #00c8d7;"
        "}"

        /* ── QLabel ── */
        "QLabel {"
        "    background-color: transparent;"
        "    color: #dde1f0;"
        "}"

        /* ── QPlainTextEdit ── */
        "QPlainTextEdit {"
        "    background-color: #0d0e18;"
        "    color: #dde1f0;"
        "    border: 1px solid #353650;"
        "    border-radius: 4px;"
        "    font-family: 'Consolas', 'Courier New', monospace;"
        "    font-size: 12px;"
        "    padding: 4px;"
        "}"

        /* ── QTextBrowser ── */
        "QTextBrowser {"
        "    background-color: #1e1f2e;"
        "    color: #dde1f0;"
        "    border: 1px solid #353650;"
        "    border-radius: 4px;"
        "    font-size: 13px;"
        "    padding: 4px;"
        "}"

        /* ── QComboBox ── */
        "QComboBox {"
        "    background-color: #252638;"
        "    color: #dde1f0;"
        "    border: 1px solid #353650;"
        "    border-radius: 3px;"
        "    padding: 3px 8px;"
        "    min-width: 80px;"
        "}"
        "QComboBox:focus {"
        "    border-color: #00c8d7;"
        "}"
        "QComboBox::drop-down {"
        "    border: none;"
        "    background-color: #353650;"
        "    width: 20px;"
        "}"
        "QComboBox QAbstractItemView {"
        "    background-color: #252638;"
        "    color: #dde1f0;"
        "    selection-background-color: #00c8d7;"
        "    selection-color: #12131a;"
        "    border: 1px solid #353650;"
        "}"

        /* ── QScrollBar:vertical ── */
        "QScrollBar:vertical {"
        "    background: #12131a;"
        "    width: 10px;"
        "    margin: 0;"
        "}"
        "QScrollBar::handle:vertical {"
        "    background: #353650;"
        "    border-radius: 5px;"
        "    min-height: 20px;"
        "}"
        "QScrollBar::handle:vertical:hover {"
        "    background: #00c8d7;"
        "}"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
        "    height: 0;"
        "}"

        /* ── QScrollBar:horizontal ── */
        "QScrollBar:horizontal {"
        "    background: #12131a;"
        "    height: 10px;"
        "    margin: 0;"
        "}"
        "QScrollBar::handle:horizontal {"
        "    background: #353650;"
        "    border-radius: 5px;"
        "    min-width: 20px;"
        "}"
        "QScrollBar::handle:horizontal:hover {"
        "    background: #00c8d7;"
        "}"
        "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {"
        "    width: 0;"
        "}"

        /* ── QScrollArea ── */
        "QScrollArea {"
        "    border: none;"
        "    background-color: #12131a;"
        "}"

        /* ── QSplitter ── */
        "QSplitter::handle {"
        "    background-color: #353650;"
        "}"
        "QSplitter::handle:horizontal {"
        "    width: 3px;"
        "}"
        "QSplitter::handle:vertical {"
        "    height: 3px;"
        "}"

        /* ── QStatusBar ── */
        "QStatusBar {"
        "    background-color: #1e1f2e;"
        "    color: #dde1f0;"
        "    border-top: 1px solid #353650;"
        "    font-size: 12px;"
        "}"
        "QStatusBar::item {"
        "    border: none;"
        "}"
    );
}

} // namespace StyleSheet

#endif // STYLESHEET_H
