#include "Tab3Help.h"

#include <QVBoxLayout>
#include <QTextBrowser>

Tab3Help::Tab3Help(QWidget *parent)
    : QWidget(parent)
    , browser_(new QTextBrowser(this))
{
    auto *layout = new QVBoxLayout(this);
    layout->setContentsMargins(8, 8, 8, 8);
    browser_->setOpenExternalLinks(false);
    browser_->setHtml(helpHtml());
    layout->addWidget(browser_);
}

QString Tab3Help::helpHtml()
{
    return QStringLiteral(
        "<!DOCTYPE html><html><head>"
        "<style>"
        "  body { background-color: #1e1f2e; color: #dde1f0; font-family: 'Segoe UI', sans-serif; "
        "         font-size: 13px; margin: 16px; line-height: 1.55; }"
        "  h1   { color: #00c8d7; border-bottom: 1px solid #353650; padding-bottom: 6px; }"
        "  h2   { color: #00c8d7; margin-top: 22px; border-bottom: 1px dotted #353650; padding-bottom: 4px; }"
        "  h3   { color: #88aacc; margin-top: 14px; }"
        "  h4   { color: #c8d0e8; margin-top: 10px; margin-bottom: 4px; }"
        "  code { background: #12131a; color: #00c8d7; font-family: Consolas, monospace; "
        "         padding: 1px 5px; border-radius: 3px; font-size: 12px; }"
        "  pre  { background: #12131a; color: #dde1f0; font-family: Consolas, monospace; "
        "         padding: 10px 12px; border-radius: 4px; border: 1px solid #353650; "
        "         font-size: 12px; overflow-x: auto; }"
        "  table { border-collapse: collapse; width: 100%; margin: 6px 0 12px; }"
        "  th    { background: #252638; color: #00c8d7; padding: 6px 10px; "
        "          border: 1px solid #353650; text-align: left; }"
        "  td    { padding: 5px 10px; border: 1px solid #353650; color: #dde1f0; "
        "          vertical-align: top; }"
        "  tr:nth-child(even) td { background: #1e1f2e; }"
        "  tr:nth-child(odd)  td { background: #252638; }"
        "  .note { background: #252638; border-left: 3px solid #ff9800; padding: 8px 12px; "
        "          margin: 10px 0; border-radius: 3px; }"
        "  .tip  { background: #252638; border-left: 3px solid #4caf50; padding: 8px 12px; "
        "          margin: 10px 0; border-radius: 3px; }"
        "  .warn { background: #2a1f1f; border-left: 3px solid #f44336; padding: 8px 12px; "
        "          margin: 10px 0; border-radius: 3px; }"
        "  ul, ol { margin-top: 4px; margin-bottom: 8px; }"
        "  .arrow_in  { color: #4caf50; }"
        "  .arrow_out { color: #ff9800; }"
        "</style>"
        "</head><body>"

        "<h1>无人机机器人控制台 &mdash; 帮助文档</h1>"
        "<p>本控制台运行在 Windows / Linux 主机上, 通过以太网与基于 RK3588 的机器人控制器通信, "
        "管理机械臂 (AgileX Piper)、无人车、机场平台、机场夹爪、深度相机, "
        "并通过 mesh 网络与无人机节点 (192.168.200.102&ndash;106) 交互。</p>"

        // ────────────────────────────────────────────────────────────────
        "<h2>1. 系统架构</h2>"
        "<pre>"
        "   ┌──────────────────────────┐                ┌────────────────────────────┐\n"
        "   │   HostGUI (Win / Linux)  │ ── TCP 7001 ── │   RK3588 / proc_gateway    │\n"
        "   │                          │   JSON-RPC     │                            │\n"
        "   │                          │ ── TCP 7002 ── │   - proc_piper             │\n"
        "   │                          │   MJPEG video  │   - proc_realsense         │\n"
        "   │                          │                │   - proc_npu (RKNN)        │\n"
        "   │                          │                │   - proc_airport (CAN3)    │\n"
        "   │                          │                │   - proc_car  (CAN1)       │\n"
        "   │                          │                │   - battery / helipad /    │\n"
        "   │                          │                │     face trackers (Py)     │\n"
        "   └──────────────────────────┘                └────────────────────────────┘\n"
        "          │                                              │\n"
        "          │ TCP 7100 (JSON, 可选)                          │ MAVLink TCP 14550\n"
        "          ▼                                              ▼\n"
        "   远端调度平台                                    无人机 mesh 节点 .102..106\n"
        "</pre>"
        "<ul>"
        "  <li><b>TCP 7001</b> &mdash; 主 JSON-RPC 通道, HostGUI 控制所有子系统</li>"
        "  <li><b>TCP 7002</b> &mdash; MJPEG 视频流 (RealSense 彩色 / 深度切换)</li>"
        "  <li><b>TCP 7100</b> &mdash; 可选远端控制, 外部调度平台下发 KMZ 任务给 HostGUI</li>"
        "  <li><b>TCP 14550</b> &mdash; HostGUI 直连无人机的 KMZ 路径下发口 (MAVLink 兼容端口)</li>"
        "</ul>"

        // ────────────────────────────────────────────────────────────────
        "<h2>2. 连接</h2>"
        "<p>在 <b>主控面板</b> 右上的连接组中:</p>"
        "<ol>"
        "  <li>填 RK3588 IP, 默认 <code>192.168.200.101</code></li>"
        "  <li>RPC 端口 <code>7001</code>, 视频端口 <code>7002</code></li>"
        "  <li>点 <b>连接</b>, LED 转绿后视频自动起 (若 \"启用视频\" 勾选)</li>"
        "</ol>"
        "<div class='note'>连接失败检查: RK3588 服务 (<code>uav-proc-gateway</code>) 是否运行 / "
        "防火墙 / 网线;视频不来可切日志过滤为 \"全部\" 看 <code>[视频]</code> 行。</div>"

        // ────────────────────────────────────────────────────────────────
        "<h2>3. 标签页一览</h2>"
        "<table>"
        "<tr><th>标签</th><th>用途</th></tr>"
        "<tr><td><b>主控面板</b></td><td>实时视频 + 各子系统手动控制 + 日志面板</td></tr>"
        "<tr><td><b>任务配置</b></td><td>9 段电池换装流程, 每段可录脚本, 支持模拟/实机/单步</td></tr>"
        "<tr><td><b>接口配置</b></td><td>RK3588 端 CAN 波特率, 串口, GPIO, 网卡参数</td></tr>"
        "<tr><td><b>帮助</b></td><td>本页面</td></tr>"
        "</table>"

        // ────────────────────────────────────────────────────────────────
        "<h2>4. 主控面板组件</h2>"

        "<h3>4.1 视频 + 检测叠加</h3>"
        "<p>RealSense BGR8 帧 (MJPEG 编码) 与 NPU/CV 检测框叠加显示。"
        "右键菜单可切深度伪彩。每 300 ms 轮询 <code>npu.get_detections</code>, "
        "支持以下类别:</p>"
        "<table>"
        "<tr><th>class_id</th><th>含义</th><th>来源</th></tr>"
        "<tr><td>4</td><td>无人机 (Mavic 3 机身)</td><td>proc_npu / mavic3_drone.rknn</td></tr>"
        "<tr><td>200</td><td>电池 (深色, 印字)</td><td>battery_tracker.py</td></tr>"
        "<tr><td>100</td><td>人脸</td><td>face_tracker.py</td></tr>"
        "<tr><td>900</td><td>平台底板 (positive empty-platform signal)</td><td>proc_npu/postprocess</td></tr>"
        "<tr><td>901</td><td>停机坪 marker (黑色圆环 + H)</td><td>helipad_tracker.py</td></tr>"
        "</table>"

        "<h3>4.2 Piper 机械臂 (gen-2)</h3>"
        "<p>6 自由度。关节滑块 / 数值框 / 笛卡尔 / 复位 / 急停 / 录当前关节。"
        "本机用 Piper SDK V1.8-2; 首次启用需 <code>STANDBY → CAN_CTRL</code> 握手 (proc_piper 自动)。</p>"

        "<h3>4.3 机场平台</h3>"
        "<p>3 条直线导轨:</p>"
        "<ul>"
        "  <li><b>导轨 1+3 联动</b> &mdash; 平台夹紧/释放, 走到电机堵转自动停</li>"
        "  <li><b>导轨 2</b> &mdash; 机场夹爪导轨, 正向(+)/负向(&minus;), 同样堵转停 (proc_gateway 监控 status 0x04/0x08)</li>"
        "  <li><b>符号约定</b> &mdash; 负方向 (&minus;) 永远是跑向零点的方向; 锁定 = (+), 释放 = (&minus;)</li>"
        "  <li><b>机场夹爪 (继电器)</b> &mdash; GPIO 继电器开合, 无位置/速度反馈</li>"
        "  <li><b>全部急停</b> &mdash; 三条导轨同时停</li>"
        "</ul>"
        "<div class='tip'>堵转检测 8 次连续 CAN 读取失败也视为堵转 (电机断线/固件挂死)。"
        "可通过 <code>UAV_AIRPORT_RAIL2_*</code> / <code>UAV_AIRPORT_LOCK_*</code> 环境变量调阈值。</div>"

        "<h3>4.4 无线 Mesh 节点</h3>"
        "<p>5 个节点 (.102&ndash;.106) 每 5 s ping 一次。绿色=在线, 灰=离线。"
        "卡片显示电量, 高度, 航向, GPS 坐标, 更新时间戳。</p>"

        "<h3>4.5 KMZ 路径规划下发</h3>"
        "<p>选 .kmz 文件 → 选目标无人机 (.102&ndash;.106 下拉) → 端口默认 14550 → 点 <b>下发</b>。"
        "走 TCP 直连, 写完即关。下方的<b>远端控制</b>面板见第 7 节详细协议。</p>"

        "<h3>4.6 轨迹跟踪 (录点 / 回放)</h3>"
        "<p>拖动机械臂 (lead-through) 到目标位姿 → 点 <b>标记</b> 捕获 J1&ndash;J6。"
        "每个点可设夹爪状态 (张开/软合/紧合) + dwell ms + 备注。"
        "保存为 JSON 后可在编辑器里精调。回放前会预检 <code>piper.get_status</code> 是否在 CAN_CTRL, "
        "并按关节行程动态算每步耗时。</p>"

        // ────────────────────────────────────────────────────────────────
        "<h2>5. 任务配置 (电池换装 9 段流程)</h2>"
        "<p>9 张卡片构成两阶段流水线 (Phase 1 = 5 段, Phase 2 = 4 段), 例如锁定 → 接近 → 抓取 → ...</p>"

        "<h3>5.1 录制 Stage 脚本</h3>"
        "<p>点卡片右上角 ⚙ 打开 StageConfigDialog。可往脚本里加各类型步骤:</p>"
        "<table>"
        "<tr><th>类型</th><th>关键参数</th><th>动作</th></tr>"
        "<tr><td>机械臂关节</td><td>J1..J6 (°), speed_ratio</td><td>arm.move_joints; 时长 = 关节最大行程 / (60·sr)</td></tr>"
        "<tr><td>机械臂笛卡尔</td><td>X/Y/Z/RX/RY/RZ, P/L</td><td>piper.move_cartesian</td></tr>"
        "<tr><td>夹爪</td><td>angle_mm, force_pct</td><td>piper.set_gripper_angle</td></tr>"
        "<tr><td>机场导轨</td>"
        "    <td>action (锁定(+) / 释放(&minus;) / 导轨2 正向(+) / 负向(&minus;)),<br>"
        "        stop_mode (堵转停 / 固定距离 / 绝对位置),<br>"
        "        speed_rpm, distance_mm, position_mm, max_ms</td>"
        "    <td>堵转停: airport.lock / release / set_speed<br>"
        "        固定距离: airport.move_mm &mdash; 相对走 N mm, 闭环编码器计数<br>"
        "        绝对位置: airport.move_to_mm &mdash; 走到距零点 N mm, <b>需先归零</b><br>"
        "        提前到位立即推进, max_ms 只是安全兜底</td></tr>"
        "<tr><td>机场夹爪</td><td>open</td><td>airport.gripper (继电器)</td></tr>"
        "<tr><td>等待识别 UAV</td><td>present, timeout_ms</td><td>轮询 class=4 出现/消失</td></tr>"
        "<tr><td>等待识别电池</td><td>present, timeout_ms</td><td>轮询 class=200</td></tr>"
        "<tr><td>延时</td><td>ms</td><td>纯等待</td></tr>"
        "</table>"

        "<h3>5.2 运行模式</h3>"
        "<ul>"
        "  <li><b>模拟</b> &mdash; 3D 视图驱动, 不发任何 RPC。"
        "  自动构建播放列表: 有脚本的 stage 走脚本步, 没脚本的走 demo 关节</li>"
        "  <li><b>实机</b> &mdash; 调 <code>swap.start</code>, proc_battery_swap 接管。"
        "  GUI 按 2 Hz 轮询 <code>swap.get_state</code> 显示进度</li>"
        "  <li><b>单步</b> &mdash; 选中一张卡片后, 点 <b>开始</b> 仅执行该 stage 的所有步骤 (脚本优先)</li>"
        "</ul>"

        // ────────────────────────────────────────────────────────────────
        "<h2>6. JSON-RPC 协议 (端口 7001)</h2>"
        "<p>持久 TCP, 每条消息一行 (\\n 终止), UTF-8 JSON。</p>"
        "<pre>"
        "请求:  {\"id\":N,\"method\":\"<ns>.<action>\",\"params\":{...}}\\n\n"
        "成功:  {\"id\":N,\"result\":{...}}\\n\n"
        "失败:  {\"id\":N,\"error\":\"<msg>\"}\\n"
        "</pre>"

        "<h3>6.1 常用方法</h3>"
        "<table>"
        "<tr><th>方法</th><th>params</th><th>说明</th></tr>"
        "<tr><td><code>system.ping</code></td><td><code>{}</code></td><td>探活</td></tr>"
        "<tr><td><code>arm.move_joints</code></td><td><code>{joints:[6], speed_ratio:float}</code></td>"
        "    <td>关节空间移动 (sr=1 → 满速)</td></tr>"
        "<tr><td><code>arm.get_angles</code></td><td><code>{}</code></td>"
        "    <td>返回当前 6 关节角度 (°)</td></tr>"
        "<tr><td><code>arm.stop</code></td><td><code>{}</code></td><td>急停</td></tr>"
        "<tr><td><code>piper.set_gripper_angle</code></td><td><code>{angle_mm:float, force_pct:int}</code></td>"
        "    <td>Piper 夹爪</td></tr>"
        "<tr><td><code>piper.get_status</code></td><td><code>{}</code></td>"
        "    <td>arm 当前模式 (CAN_CTRL / STANDBY / ESTOP)</td></tr>"
        "<tr><td><code>airport.lock</code> / <code>airport.release</code></td>"
        "    <td><code>{speed_rpm:int}</code></td>"
        "    <td>导轨 1+3 联动夹紧/释放, 堵转停</td></tr>"
        "<tr><td><code>airport.set_speed</code></td>"
        "    <td><code>{rail:0|1|2, speed_rpm:int}</code></td>"
        "    <td>单导轨速度 (rail=1 即 UI 导轨 2, 堵转停)</td></tr>"
        "<tr><td><code>airport.set_rail</code></td>"
        "    <td><code>{rail, pos_mm:float, speed_rpm}</code></td>"
        "    <td>导轨绝对位置 (开环, 无堵转)</td></tr>"
        "<tr><td><code>airport.stop</code> / <code>airport.stop_all</code></td><td><code>{rail?}</code></td>"
        "    <td>停一条 / 全停</td></tr>"
        "<tr><td><code>airport.gripper</code></td><td><code>{open:bool}</code></td>"
        "    <td>机场夹爪继电器</td></tr>"
        "<tr><td><code>car.set_velocity</code></td><td><code>{vx, vy, omega}</code></td>"
        "    <td>底盘速度</td></tr>"
        "<tr><td><code>npu.get_detections</code></td><td><code>{}</code></td>"
        "    <td>当前检测框列表 (含 drone / battery / platform / helipad)</td></tr>"
        "<tr><td><code>npu.set_threshold</code></td><td><code>{threshold:0..1}</code></td>"
        "    <td>调置信度门限 (默认 0.55)</td></tr>"
        "<tr><td><code>npu.set_strategy</code></td><td><code>{strategy:int}</code></td>"
        "    <td>切策略 (0=默认, 4=BatteryCV, 5=Mavic3Drone, ...)</td></tr>"
        "<tr><td><code>video.set_enabled</code></td><td><code>{enabled:bool}</code></td>"
        "    <td>启停视频流</td></tr>"
        "<tr><td><code>video.set_source</code></td><td><code>{source:\"rgb\"|\"depth\"}</code></td>"
        "    <td>切 RGB / 深度伪彩</td></tr>"
        "<tr><td><code>system.get_logs</code></td><td><code>{source:str, max_lines:int}</code></td>"
        "    <td>拉远端 proc_* journald 日志</td></tr>"
        "<tr><td><code>calib.set_hand_eye</code></td><td><code>{matrix:[16]}</code></td>"
        "    <td>下发手眼标定矩阵到 proc_grasp</td></tr>"
        "</table>"

        // ────────────────────────────────────────────────────────────────
        "<h2>7. 远端 KMZ 控制 (端口 7100, JSON over TCP)</h2>"
        "<p>HostGUI 主控面板的 <b>KMZ 路径规划下发 → 远端控制</b> 子面板可开启一个"
        "<b>line-delimited JSON</b> 监听端口, 让外部调度平台远程触发 KMZ 下发。"
        "默认端口 <code>7100</code>, 可改;KMZ 库目录默认 <code>~/Documents/UAV_KMZ</code>, 可改。"
        "端口和目录都通过 QSettings 持久化, 重启保留。</p>"

        "<div class='note'>开启后 HostGUI 在 <code>0.0.0.0:&lt;port&gt;</code> 接 TCP 连接, "
        "每条消息一行 JSON (<code>\\n</code> 结尾), UTF-8 编码。"
        "id 用于请求/响应匹配, HostGUI 在响应里原样回填。</div>"

        "<h3>7.1 协议总览</h3>"
        "<table>"
        "<tr><th>cmd</th><th>用途</th><th>响应阶段</th></tr>"
        "<tr><td><code>ping</code></td><td>探活</td><td>立即返回 ok</td></tr>"
        "<tr><td><code>list_kmz</code></td><td>列出库目录里所有 *.kmz</td><td>立即返回</td></tr>"
        "<tr><td><code>deploy_kmz</code></td><td>从库找文件并下发给无人机</td>"
        "    <td>先 <code>accepted</code>, 完成后 <code>done</code> / 失败 <code>send_error</code></td></tr>"
        "</table>"

        "<h3>7.2 ping</h3>"
        "<pre>"
        "<span class='arrow_out'>→</span> {\"id\":1,\"cmd\":\"ping\"}\n"
        "<span class='arrow_in'>←</span> {\"id\":1,\"cmd\":\"ping\",\"ok\":true}\n"
        "</pre>"

        "<h3>7.3 list_kmz</h3>"
        "<pre>"
        "<span class='arrow_out'>→</span> {\"id\":2,\"cmd\":\"list_kmz\"}\n"
        "<span class='arrow_in'>←</span> {\n"
        "    \"id\": 2,\n"
        "    \"cmd\": \"list_kmz\",\n"
        "    \"ok\": true,\n"
        "    \"dir\": \"C:/Users/Op/Documents/UAV_KMZ\",\n"
        "    \"files\": [\"plan_alpha.kmz\", \"plan_bravo.kmz\", \"survey_03.kmz\"]\n"
        "}\n"
        "</pre>"
        "<p>错误时:</p>"
        "<pre>"
        "<span class='arrow_in'>←</span> {\"id\":2,\"cmd\":\"list_kmz\",\"ok\":false,\"error\":\"kmz dir not found: ...\"}\n"
        "</pre>"

        "<h3>7.4 deploy_kmz</h3>"
        "<p>下发流程分两步响应: 接受 (<code>accepted</code>) → 完成 (<code>done</code>)。两条响应共享同一 id。"
        "<code>name</code> 可省 <code>.kmz</code> 扩展;含 <code>..</code> / <code>/</code> / <code>\\</code> 直接拒(防穿目录)。"
        "<code>target</code>/<code>port</code> 省略时用 GUI 上下拉框/spinbox 当前值。</p>"

        "<h4>请求</h4>"
        "<pre>"
        "<span class='arrow_out'>→</span> {\n"
        "    \"id\": 3,\n"
        "    \"cmd\": \"deploy_kmz\",\n"
        "    \"name\": \"plan_alpha\",                <span style='color:#7f8aa3'>// 或 \"plan_alpha.kmz\"</span>\n"
        "    \"target\": \"192.168.200.102\",          <span style='color:#7f8aa3'>// 可选, 默认下拉框</span>\n"
        "    \"port\": 14550                       <span style='color:#7f8aa3'>// 可选, 默认 14550</span>\n"
        "}\n"
        "</pre>"

        "<h4>接受 (interim ack, 文件已读入内存, 开始 TCP 连无人机)</h4>"
        "<pre>"
        "<span class='arrow_in'>←</span> {\n"
        "    \"id\": 3,\n"
        "    \"cmd\": \"deploy_kmz\",\n"
        "    \"ok\": true,\n"
        "    \"stage\": \"accepted\",\n"
        "    \"name\": \"plan_alpha\",\n"
        "    \"resolved\": \"C:/.../UAV_KMZ/plan_alpha.kmz\",\n"
        "    \"target\": \"192.168.200.102\",\n"
        "    \"port\": 14550,\n"
        "    \"bytes\": 12345\n"
        "}\n"
        "</pre>"

        "<h4>完成 (写完字节后无人机端关闭连接)</h4>"
        "<pre>"
        "<span class='arrow_in'>←</span> {\n"
        "    \"id\": 3,\n"
        "    \"cmd\": \"deploy_kmz\",\n"
        "    \"ok\": true,\n"
        "    \"stage\": \"done\",\n"
        "    \"name\": \"plan_alpha\",\n"
        "    \"bytes\": 12345,\n"
        "    \"target\": \"192.168.200.102\",\n"
        "    \"port\": 14550\n"
        "}\n"
        "</pre>"

        "<h4>失败示例</h4>"
        "<pre>"
        "<span style='color:#7f8aa3'>// 库里找不到该文件</span>\n"
        "<span class='arrow_in'>←</span> {\"id\":3,\"cmd\":\"deploy_kmz\",\"ok\":false,\n"
        "    \"error\":\"file not found: plan_zzz (in C:/.../UAV_KMZ)\"}\n"
        "\n"
        "<span style='color:#7f8aa3'>// 已有下发在跑 (并发拒绝)</span>\n"
        "<span class='arrow_in'>←</span> {\"id\":3,\"cmd\":\"deploy_kmz\",\"ok\":false,\n"
        "    \"error\":\"busy: a remote deployment is already in progress\"}\n"
        "\n"
        "<span style='color:#7f8aa3'>// 连无人机失败 / 中途断开</span>\n"
        "<span class='arrow_in'>←</span> {\"id\":3,\"ok\":false,\"stage\":\"send_error\",\n"
        "    \"error\":\"<socket error message>\",\"name\":\"plan_alpha\"}\n"
        "</pre>"

        "<h3>7.5 错误情况速查</h3>"
        "<table>"
        "<tr><th>错误 error 字段</th><th>原因</th></tr>"
        "<tr><td>parse error: ...</td><td>JSON 格式非法</td></tr>"
        "<tr><td>unknown cmd: ...</td><td>cmd 字段不在 ping/list_kmz/deploy_kmz 之中</td></tr>"
        "<tr><td>missing 'name'</td><td>deploy_kmz 缺 name 字段</td></tr>"
        "<tr><td>file not found: ...</td><td>name 在库目录里找不到对应文件</td></tr>"
        "<tr><td>open failed: ...</td><td>找到文件但读不动 (权限/锁)</td></tr>"
        "<tr><td>file is empty</td><td>文件存在但 0 字节</td></tr>"
        "<tr><td>busy: ...</td><td>已有下发在跑 (手动或远端)</td></tr>"
        "<tr><td>kmz dir not found: ...</td><td>库目录配的路径不存在</td></tr>"
        "</table>"

        "<h3>7.6 远端控制 — Python 快速验证</h3>"
        "<pre>"
        "import socket, json\n"
        "s = socket.create_connection(('192.168.1.50', 7100))\n"
        "f = s.makefile('rw', encoding='utf-8', newline='\\n')\n"
        "\n"
        "<span style='color:#7f8aa3'># 列文件</span>\n"
        "f.write(json.dumps({'id':1, 'cmd':'list_kmz'}) + '\\n'); f.flush()\n"
        "print('list:', json.loads(f.readline()))\n"
        "\n"
        "<span style='color:#7f8aa3'># 下发</span>\n"
        "f.write(json.dumps({'id':2, 'cmd':'deploy_kmz',\n"
        "                     'name':'plan_alpha',\n"
        "                     'target':'192.168.200.102'}) + '\\n')\n"
        "f.flush()\n"
        "print('accepted:', json.loads(f.readline()))\n"
        "print('done:    ', json.loads(f.readline()))\n"
        "</pre>"
        "<div class='tip'>同一连接里可以连续发多条命令, HostGUI 按 id 回复, 顺序与请求一致 (deploy_kmz 因要等无人机回包, 它的 done 可能晚于后续 ping 的回复 — 用 id 匹配, 别用顺序)。</div>"

        // ────────────────────────────────────────────────────────────────
        "<h2>8. 视频流 (端口 7002)</h2>"
        "<p>MJPEG, 每帧长度前缀:</p>"
        "<pre>[uint32 BE = JPEG 长度] [JPEG bytes...]</pre>"
        "<p>视频与 RPC 各自独立 TCP, 断开自动重连。3 s 无帧 → 控件显示 <b>无信号</b>。"
        "RGB / 深度伪彩通过 <code>video.set_source</code> 切换。</p>"

        // ────────────────────────────────────────────────────────────────
        "<h2>9. 接口配置 (Tab 2)</h2>"
        "<p>用于调 RK3588 端硬件参数, 改完通过 RPC 持久化到机器人配置文件 (重启生效)。"
        "<b>不影响</b> HostGUI 到 RK3588 的 TCP 连接 (那块用主控面板的连接组改)。</p>"
        "<ul>"
        "  <li><b>CAN 总线</b>: <code>can1</code> = 平台直线电机, <code>can3</code> = 小车, <code>can4</code> = 机械臂 (legacy)</li>"
        "  <li><b>串口</b>: 机械臂夹爪 (UART), 默认 <code>/dev/ttyUSB0</code> @ 115200</li>"
        "  <li><b>GPIO 继电器</b>: 机场夹爪通道选择 (<code>/sys/devices/platform/gpio-innohi/...</code>)</li>"
        "  <li><b>网卡</b>: 主控连接的 RPC/视频端口监听地址</li>"
        "</ul>"

        // ────────────────────────────────────────────────────────────────
        "<h2>10. 日志面板</h2>"
        "<p>主控面板和任务配置标签下方各有一个 LogWidget。源默认 <b>本地</b> (HostGUI 自身); "
        "可切到任意 <code>proc_*</code> 远端日志 (1.5 Hz 轮询 <code>system.get_logs</code>)。</p>"
        "<ul>"
        "  <li>级别下拉默认 <b>错误</b> (减少噪声), 调试时切 <b>信息</b> / <b>全部</b></li>"
        "  <li>选择会自动存到 <code>HostGUI.ini</code>, 下次启动保留</li>"
        "  <li>颜色: <span style='color:#dde1f0'>INFO 白</span> / "
        "       <span style='color:#ff9800'>WARN 橙</span> / "
        "       <span style='color:#f44336'>ERROR 红</span></li>"
        "</ul>"

        // ────────────────────────────────────────────────────────────────
        "<h2>11. 故障排查</h2>"
        "<table>"
        "<tr><th>症状</th><th>排查</th></tr>"
        "<tr><td>连接后没有视频</td>"
        "    <td>切日志过滤 \"全部\" 看 <code>[视频]</code> 行;"
        "        检查 \"启用视频\" radio 是否勾选;"
        "        后端 <code>journalctl -u uav-proc-realsense</code></td></tr>"
        "<tr><td>无人机框 (class=4) 不停闪</td>"
        "    <td>已加 5 帧 Schmitt 滞后 + IoU 0.55 帧间确认 + 中心必须在平台内, "
        "        若仍闪可能是 mavic3_drone.rknn 在你场景下 phantoms 太多, 调 npu.set_threshold</td></tr>"
        "<tr><td>机场导轨不停</td>"
        "    <td>proc_gateway 的 monitor_*_until_stall 没读到 status 0x04/0x08; "
        "        检查 CAN 接线 / 总线波特率;"
        "        UAV_AIRPORT_*_MAX_MS 兜底也会强停</td></tr>"
        "<tr><td>远端 JSON 连不上</td>"
        "    <td>侦听 toggle 没开 / 端口被占;"
        "        防火墙;"
        "        HostGUI 状态行应显示 \"侦听中 0.0.0.0:7100\"</td></tr>"
        "<tr><td>HostGUI 启动闪退</td>"
        "    <td>Windows 看 Event Viewer → Application → WER APPCRASH;"
        "        检查 Qt 6.11 + MinGW 13.1 运行时齐全 (libstdc++-6.dll, libgcc_s_seh-1.dll, libwinpthread-1.dll)</td></tr>"
        "</table>"

        "<div class='tip'>意见反馈 / bug report: 直接说现象 + 重现步骤, "
        "尤其要带日志面板的 ERROR 行 (切到 \"全部\" 复制一段)。</div>"

        "</body></html>"
    );
}
